CREATE TABLE BRAND (
    ID      INTEGER NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(10),
    PRIMARY KEY(ID)
);

CREATE TABLE PRODUCT (
    ID          INTEGER NOT NULL AUTO_INCREMENT,
    BRAND_ID    INTEGER NOT NULL,
    START_DATE  TIMESTAMP NOT NULL,
    END_DATE    TIMESTAMP NOT NULL,
    PRICE_LIST  INTEGER NOT NULL,
    PRODUCT_ID  INTEGER NOT NULL,
    PRIORITY    INTEGER NOT NULL,
    PRICE       NUMERIC(5,2) NOT NULL,
    CURR        VARCHAR(3) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_BrandId FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);